"""empty message

Revision ID: 47bd35d8de69
Revises: 748815cee56c
Create Date: 2020-04-11 14:20:52.022763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bd35d8de69'
down_revision = '748815cee56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'title')
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
