"""empty message

Revision ID: 748815cee56c
Revises: 
Create Date: 2020-04-11 14:09:07.076378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748815cee56c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('actors', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'name')
    op.drop_column('actors', 'gender')
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###
