"""empty message

Revision ID: fc3d40b85655
Revises: f55f56cb4741
Create Date: 2020-04-12 13:26:38.593014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3d40b85655'
down_revision = 'f55f56cb4741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('synopsis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'synopsis')
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
